export const allproducts=[
    {   id:1,
        name:"Dining Chair",
        image:"https://www.epichomeideas.com/wp-content/uploads/2017/12/dining-chair1.jpg",
        price:80,
        des:"According to the Old Testament, chairs were reserved for Pharaohs and kings, serving as thrones rather than seating",
        pricetype:"lowprice",
        category:"old category",
        rate:"4.00",
        types:"cusion",
        stocks:"in stock terms 300 items",
    },
    {
        id:2,
        name:"Scroll-Back Dining Chairs",
        image:"https://www.homestratosphere.com/wp-content/uploads/2023/10/Prado-De-La-Felicidad-Scroll-Back-Dining-Chair-1022023.jpg",
        des:"Scroll-back dining chairs are characterized by their gracefully curved backs, which often take on a scroll or wave-like shape",
        price:75,
        pricetype:"lowprice",
        category:"new",
        rate:"3.00",
        types:"plastic",
        stocks:"in stock terms 400 items",
    },
    { id:3,
        name:"Parsons Chair",
        image:"https://www.homestratosphere.com/wp-content/uploads/2014/12/parsonschair.jpg",
        des:"simple dining chair with clean lines that would fit nicely into just about any area of the home and is in the category of upholstered dining chairs.",
        price:50,
        category:"new",
        rate:"4.00",
        types:"cusion",
        pricetype:"lowprice",
        stocks:"in stock terms 100 items",
    },
    {   id:4,
        name:"Metal",
        image:"https://www.homestratosphere.com/wp-content/uploads/2014/12/metalseatchair-1536x1536.jpeg",
        des:"The armchair features, as one would guess, arms in addition to the traditional side chair design.",
        category:"new",
        pricetype:"highprice",
        rate:"3.4",
        types:"metal",
        price:250,
        stocks:"in stock terms 200 items",
    },
    
    {   id:5,
        name:"Arm Chair",
        image:"https://cdn-fastly.upgradedhome.com/media/2023/07/31/9087292/17-different-types-of-dining-chairs.jpg?size=720x845&nocrop=1",
        des:"The armchair features, as one would guess, arms in addition to the traditional side chair design.",
        pricetype:"highprice",
        category:"old",
        rate:"4.00",
        types:"cusion",
        price:140,
        stocks:"in stock terms 220 items",
    },
    {   id:6,
        name:"Bar Stool",
        image:"https://cdn-fastly.upgradedhome.com/media/2023/07/31/9087301/17-different-types-of-dining-chairs.jpg?size=720x845&nocrop=1",
        des:"Bar stools are a great choice for many rooms in the house, such as kitchens, bars, sunrooms, and even dining rooms",
        price:100,
        pricetype:"lowprice",
        category:"new",
        rate:"3.6",
        types:"wood",
        stocks:"in stock terms 60 items",
    },
    {   id:7,
        name:"Wood frame",
        image:"https://cdn-fastly.upgradedhome.com/media/2023/07/31/9087304/17-different-types-of-dining-chairs.jpg?size=720x845&nocrop=1",
        des:"These chairs are fitted with wicker frames to create a distinct and memorable outline around the upholstered seat",
        price:30,
        pricetype:"lowprice",
        category:"old",
        rate:"3.4",
        types:"wood",
        stocks:"in stock terms 200 items",
    },
    {   id:8,
        name:"Plastic Frame",
        image:"https://cdn-fastly.upgradedhome.com/media/2023/07/31/9087319/17-different-types-of-dining-chairs.jpg?size=720x845&nocrop=1",
        des:"Plastic frame chairs are a durable and comfortable alternative to wicker frame chairs that aren’t as expensive",
        price:180,
        pricetype:"highprice",
        category:"old",
        rate:"3.4",
        types:"plastic",
        stocks:"in stock terms 100 items",
    },
    {   id:9,
        image:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1580742487-resize.jpg?crop=0.800xw:1xh;center,top&resize=980:*",
        name:"Eero Saarinen Tulip",
        price:40,
        des:"Finnish American architect and designer Eero Saarinen famously hated the sight of many table and chair legs in a room, calling it an “ugly, confusing, unrestful world.",
        type:"lowprice",
        category:"new",
        rate:"4.00",
        types:"plastic",
        stocks:"in stock terms 150 items",
    },
    {   id:10,
        image:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1580745198-PD_2582_MAIN.jpg?crop=0.504xw:1xh;center,top&resize=980:*",
        name:"Hans Wegner Chair",
        price:60,
        des:"Designed to mimic the curving shape of a bicycle handlebar, this type of chair has been a design staple since Marcel Bruer first constructed it",
        pricetype:"lowprice",
        category:"new",
        rate:"4.00",
        types:"wood",
        stocks:"in stock terms 120 items",
           
    },
   
    
    {   id:11,
        image:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1718216281-YareliArmchair.jpg?crop=0.800xw:1xh;center,top&resize=980:*",
        name:"Morettis Armchair",
        price:150,
        des:"Comfort was prioritized for the 2nd chair iteration of the middle—Louis XV period (1723-1750)",
        pricetype:"highprice",
        category:"old",
        rate:"4.0",
        types:"metal",
        stocks:"in stock terms 180 items",
           
    },
    {   id:12,
        image:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1707857039-f_32579772_1675440440780_bg_processed.jpg?crop=0.800xw:1xh;center,top&resize=980:*",
        name:"1stDibs Vintage Chair",
        price:180,
        des:"These armchairs, originally handcrafted for royal members of the Yoruba tribes of western Africa, are covered in a pattern created entirely from beads",
        pricetype:"highprice",
        category:"new",
        rate:"4.00",
        types:"cusion",
        stocks:"in stock terms 190 items",
    },
    {   id:13,
        image:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1718215738-screenshot-2024-06-12-at-2-08-28-pm-6669e42281a24.png?crop=0.9397260273972602xw:1xh;center,top&resize=980:*",
        name:"Eero Womb Chair",
        price:230,
        des:"When Eero Saarinen began working with Florence Knoll, she challenged him to create the world's most comfortable chair",
        pricetype:"highprice",
        category:"old",
        rate:"4.00",
        types:"cusion",
        stocks:"in stock terms 110 items",  
    }
   
]